=== kamilaLukaszPlodzpl/technologie-xml/video_games.xsd
<?xml version="1.0"?>

<xs:schema
        xmlns:xs="http://www.w3.org/2001/XMLSchema"
        xmlns="video_games"
        xmlns:en="enumerations"
        targetNamespace="video_games"
>
<xs:import schemaLocation="enumerations.xsd" namespace="enumerations"/>

<!-- Deklaracje -->
<!-- Głowne elementy -->
<xs:element name="root" type="RootType">

    <xs:key name="keyPlatform">
        <xs:selector xpath=".//root/data/platforms/platform"/>
        <xs:field xpath="@id"/>
    </xs:key>
    <xs:key name="keyGenre">
        <xs:selector xpath=".//root/data/genres/genre"/>
        <xs:field xpath="@id"/>
    </xs:key>
    <xs:key name="keyPegiDescriptors">
        <xs:selector xpath=".//root/data/pegiDescriptors/pegiDescriptor"/>
        <xs:field xpath="@id"/>
    </xs:key>

    <xs:keyref name="keyRefPlatform" refer="keyPlatform">
        <xs:selector xpath=".//root/data/games/game/PEGI/relatedPegi"/>
        <xs:field xpath="@id"/>
    </xs:keyref>
    <xs:keyref name="keyRefGenre" refer="keyGenre">
        <xs:selector xpath=".//root/data/games/game/relatedGenre"/>
        <xs:field xpath="@id"/>
    </xs:keyref>
    <xs:keyref name="keyRefPegiDescriptors" refer="keyPegiDescriptors">
        <xs:selector xpath=".//root/data/games/game/relatedPlatforms/relatedPlatform"/>
        <xs:field xpath="@id"/>
    </xs:keyref>
</xs:element>

<xs:complexType name="RootType">
    <xs:sequence>
        <xs:element name="description" type="DescriptionType"/>
        <xs:element name="data" type="DataType"/>
        <xs:element name="authors" type="AuthorsType"/>
    </xs:sequence>
</xs:complexType>

<xs:simpleType name="DescriptionType">
    <xs:restriction base="xs:string"/><!-- TODO: Fix it -->
</xs:simpleType>
<xs:complexType name="DataType">
    <xs:sequence>
        <xs:element name="platforms" type="PlatformsType"/>
        <xs:element name="genres" type="GenresType"/>
        <xs:element name="pegiDescriptors" type="PegiDescriptorsType"/>
        <xs:element name="games" type="GamesType"/>
    </xs:sequence>
    <xs:attribute name="dataSource" type="xs:anyURI"/>
</xs:complexType>
<xs:complexType name="AuthorsType">
    <xs:sequence>
        <xs:element name="person" type="PersonType" maxOccurs="unbounded"/>
    </xs:sequence>
</xs:complexType>
<!-- Typy wewnątrz DataType -->
<xs:complexType name="PlatformsType">
    <xs:sequence>
        <xs:element name="platform" type="PlatformType" maxOccurs="unbounded"/>
    </xs:sequence>
</xs:complexType>
    <xs:complexType name="PlatformType">
        <xs:simpleContent>
            <xs:extension base="en:PlatformEnumType">
                <xs:attribute name="id" type="IdType"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

<xs:complexType name="GenresType">
    <xs:sequence>
        <xs:element name="genre" type="GenreType" maxOccurs="unbounded"/>
    </xs:sequence>
</xs:complexType>
    <xs:complexType name="GenreType">
        <xs:simpleContent>
            <xs:extension base="en:GenreEnumType">
                <xs:attribute name="id" type="IdType"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

<xs:complexType name="PegiDescriptorsType">
    <xs:sequence>
        <xs:element name="pegiDescriptor" type="PegiDescriptorType" maxOccurs="unbounded"/>
    </xs:sequence>
</xs:complexType>
    <xs:complexType name="PegiDescriptorType">
        <xs:simpleContent>
            <xs:extension base="en:PegiDescriptorEnumType">
                <xs:attribute name="id" type="IdType"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

<xs:complexType name="GamesType">
    <xs:sequence>
        <xs:element name="game" type="GameType" maxOccurs="unbounded"/>
    </xs:sequence>
</xs:complexType>
    <xs:complexType name="GameType">
        <xs:sequence>
            <xs:element name="title" type="TitleType"/>
            <xs:element name="price" type="PriceType" minOccurs="0"/>
            <xs:element name="relatedGenre" type="RelatedGenreType"/>
            <xs:element name="releaseDate" type="DateType"/>
            <xs:element name="developer" type="DeveloperType"/>
            <xs:element name="relatedPlatforms" type="RelatedPlatformsType"/>
            <xs:element name="publisher" type="PublisherType"/>
            <xs:element name="rating" type="RatingType"/>
            <xs:element name="PEGI" type="PegiType"/>
            <xs:element name="coverArt" type="CoverArtType"/>
        </xs:sequence>
        <xs:attribute name="id" type="IdType"/>
    </xs:complexType>
<!-- Typy wewnątrz GameType -->

<xs:complexType name="TitleType">
    <xs:simpleContent>
        <xs:extension base="TitleContentType">
            <xs:attribute name="language" type="LanguageType"/>
        </xs:extension>
    </xs:simpleContent>
</xs:complexType>
    <xs:simpleType name="TitleContentType">
        <xs:restriction base="xs:string">
            <xs:whiteSpace value="collapse"/>
            <xs:minLength value="1"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="LanguageType">
        <xs:restriction base="xs:string">
            <xs:whiteSpace value="replace"/>
            <xs:minLength value="1"/>
            <xs:pattern value="([a-z])*"/>
        </xs:restriction>
    </xs:simpleType>

<xs:complexType name="PriceType">
    <xs:simpleContent>
        <xs:extension base="PriceContentType">
            <xs:attribute name="currency" type="CurrencyType"/>
        </xs:extension>
    </xs:simpleContent>
</xs:complexType>
    <xs:simpleType name="PriceContentType">
        <xs:restriction base="xs:decimal">
            <xs:whiteSpace value="collapse"/>
            <xs:fractionDigits value="2"/>
            <xs:minInclusive value="0"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="CurrencyType">
        <xs:restriction base="xs:string">
            <xs:whiteSpace value="replace"/>
            <xs:minLength value="1"/>
            <xs:pattern value="([a-z])*"/>
        </xs:restriction>
    </xs:simpleType>

<xs:complexType name="RelatedGenreType">
    <xs:attribute name="id" type="IdType"/>
</xs:complexType>

<xs:simpleType name="DeveloperType">
    <xs:restriction base="xs:string">
        <xs:whiteSpace value="collapse"/>
        <xs:minLength value="1"/>
    </xs:restriction>
</xs:simpleType>

<xs:complexType name="RelatedPlatformsType">
    <xs:sequence>
        <xs:element name="relatedPlatform" type="RelatedPlatformType" maxOccurs="unbounded"/>
    </xs:sequence>
</xs:complexType>
    <xs:complexType name="RelatedPlatformType">
        <xs:attribute name="id" type="IdType"/>
    </xs:complexType>
    
<xs:simpleType name="PublisherType">
    <xs:restriction base="xs:string"/>
</xs:simpleType>
<xs:complexType name="RatingType">
    <xs:simpleContent>
        <xs:extension base="RatingContentType">
            <xs:attribute name="source" type="xs:string"/>
            <xs:attribute name="max" type="RatingMaxAttributeType"/>
        </xs:extension>
    </xs:simpleContent>
</xs:complexType>
    <xs:simpleType name="RatingContentType">
        <xs:restriction base="xs:decimal">
            <xs:minInclusive value="0"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="RatingMaxAttributeType">
        <xs:restriction base="xs:positiveInteger"/>
    </xs:simpleType>
    
<xs:complexType name="PegiType">
    <xs:sequence>
        <xs:element name="relatedPegi" type="RelatedPegiType" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute name="label" type="IdType"/>
</xs:complexType>
    <xs:complexType name="RelatedPegiType">
        <xs:attribute name="id" type="IdType"/>
    </xs:complexType>

<xs:complexType name="CoverArtType">
    <xs:attribute name="src" type="xs:anyURI"/>
</xs:complexType>

<!-- Typy wewnątrz AuthorsType -->
<xs:complexType name="PersonType">
    <xs:all>
        <xs:element name="name" type="PersonNameType"/>
        <xs:element name="surname" type="PersonSurnameType"/>
        <xs:element name="index" type="StudentIndexType"/>
    </xs:all>
</xs:complexType>
    <xs:simpleType name="PersonNameType">
        <xs:restriction base="xs:string"/>
    </xs:simpleType>
    <xs:simpleType name="PersonSurnameType">
        <xs:restriction base="xs:string"/>
    </xs:simpleType>
    <xs:simpleType name="StudentIndexType">
        <xs:restriction base="xs:positiveInteger">
            <xs:totalDigits value="6"/>
            <xs:minInclusive value="100000"/>
            <xs:maxInclusive value="999999"/>
        </xs:restriction>
    </xs:simpleType>
<!-- Typy wspólne -->
<xs:simpleType name="IdType">
    <xs:restriction base="xs:ID">
    </xs:restriction>
</xs:simpleType>
<xs:simpleType name="TextType">
    <xs:restriction base="xs:string">
        <xs:whiteSpace value="preserve"/>
    </xs:restriction>
</xs:simpleType>
<xs:complexType name="DateType">
    <xs:sequence>
        <xs:element name="day" type="DayType"/>
        <xs:element name="month" type="en:MonthEnumType"/>
        <xs:element name="year" type="YearType"/>
    </xs:sequence>
</xs:complexType>
    <xs:simpleType name="DayType">
        <xs:restriction base="xs:positiveInteger">
            <xs:maxInclusive value="31"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="YearType">
        <xs:restriction base="xs:positiveInteger">
            <xs:totalDigits value="4"/>
        </xs:restriction>
    </xs:simpleType>
<!-- Koniec deklaracji -->
</xs:schema>

=== kamilaLukaszPlodzpl/technologie-xml/zadaanie5/xmlapp/src/assets/video_games.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<?xml-stylesheet href="style.css" type="text/css;charset=UTF-8"?>
<?xml-stylesheet href="style.css" type="text/css"?>
<?xml-stylesheet type="text/xsl" href="video_games_support.xsl"?>

<root
    xmlns="video_games"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="video_games video_games.xsd"
>

    <description>Spis gier</description>

    <data dataSource="https://www.gry-online.pl/gry/">
        <platforms>
            <platform id="p1">PlayStation 3</platform>
            <platform id="p2">PlayStation 4</platform>
            <platform id="p3">PlayStation 2</platform>
            <platform id="p4">Microsoft Windows</platform>
            <platform id="p5">Xbox One</platform>
            <platform id="p6">macOS</platform>
            <platform id="p7">Linux</platform>
            <platform id="p8">Xbox 360</platform>
            <platform id="p9">Nintendo Switch</platform>
            <platform id="p10">Xbox</platform>
            <platform id="p11">Android</platform>
        </platforms>
        <genres>
            <genre id="g1">hack and slash</genre>
            <genre id="g2">skradanka</genre>
            <genre id="g3">survival</genre>
            <genre id="g4">piaskownica</genre>
            <genre id="g5">strategia</genre>
            <genre id="g6">strzelanka</genre>
            <genre id="g7">wyścigi</genre>
            <genre id="g8">MMO</genre> 
            <genre id="g9">symulacja</genre> 
            <genre id="g10">akcji</genre>
            <genre id="g11">RPG</genre>
        </genres>
		<pegiDescriptors>
			<pegiDescriptor id="d1">przemoc</pegiDescriptor>
			<pegiDescriptor id="d2">wulgarny język</pegiDescriptor>
			<pegiDescriptor id="d3">strach</pegiDescriptor>
			<pegiDescriptor id="d4">hazard</pegiDescriptor>
			<pegiDescriptor id="d5">seks</pegiDescriptor>
            <pegiDescriptor id="d6">online</pegiDescriptor>
		</pegiDescriptors>
		
        <games>
            <game id="game1">
                <title language="angielski">God of War III</title>
                <price currency="zł">239.90</price>
                <relatedGenre id="g1"/>
                <releaseDate>
                    <day>16</day>
                    <month>Marzec</month>
                    <year>2010</year>
                </releaseDate>
                <developer>SCE Santa Monica Studio</developer>
                <relatedPlatforms>
                    <relatedPlatform id="p1"/>
                    <relatedPlatform id="p2"/>
                </relatedPlatforms>
                <publisher>Sony Computer Entertainment</publisher>
				<rating source="Gry-Online" max="10">9.1</rating>
				<PEGI label="18"> 
                    <relatedPegi id="d1"/>
				</PEGI>
                <coverArt src="id1.jpg"/>
            </game>

            <game id="game2">
                <title language="angielski">Hitman 2</title>
                <price currency="zł">249.00</price>
                <relatedGenre id="g2"/>
                <releaseDate>
                    <day>13</day>
                    <month>Listopad</month>
                    <year>2018</year>
                </releaseDate>
                <developer>IO Interactive</developer>
                <relatedPlatforms>
                    <relatedPlatform id="p2"/>
                    <relatedPlatform id="p4"/>
                    <relatedPlatform id="p5"/>
                </relatedPlatforms>
                <publisher>Warner Bros. Interactive Entertainment</publisher>
				<rating source="Gry-Online" max="10">7.6</rating>
				<PEGI label="18"> 
                    <relatedPegi id="d1"/>
                    <relatedPegi id="d2"/>
				</PEGI>
                <coverArt src="id2.jpg"/>
            </game>

            <game id="game3">
                <title language="angielski">Minecraft: Java Edition</title>
                <price currency="zł">99.99</price>
                <relatedGenre id="g3"/>
                <releaseDate>
                    <day>18</day>
                    <month>Listopad</month>
                    <year>2011</year>
                </releaseDate>
                <developer>Mojang</developer>
                <relatedPlatforms>
                    <relatedPlatform id="p4"/>
                    <relatedPlatform id="p6"/> 
                    <relatedPlatform id="p7"/> 
                </relatedPlatforms>
                <publisher>Mojang</publisher>
				<rating source="Metacritics" max="10">7.6</rating>
				<PEGI label="7"> 
                    <relatedPegi id="d3"/>
                    <relatedPegi id="d1"/>
                    <relatedPegi id="d6"/>
				</PEGI>
                <coverArt src="id3.jpg"/>
            </game>

            <game id="game4">
                <title language="angielski">Garry's Mod</title>
                <price currency="zł">35.99</price>
                <relatedGenre id="g4"/>
                <releaseDate>
                    <day>24</day>
                    <month>Grudzień</month>
                    <year>2004</year>
                </releaseDate>
                <developer>Facepunch Studios</developer>
                <relatedPlatforms> 
                    <relatedPlatform id="p4"/>
                    <relatedPlatform id="p6"/> 
                    <relatedPlatform id="p7"/>
                </relatedPlatforms>
                <publisher>Valve Corporation</publisher>
				<rating source="Gry-Online" max="10">9.1</rating>
				<PEGI label="odpowiednia dla każdego wieku"> 
				</PEGI>
                <coverArt src="id4.jpg"/>
            </game>

            <game id="game5">
                <title language="angielski">John Wick Hex</title>
                <price currency="zł">69.00</price>
                <relatedGenre id="g5"/>
                <releaseDate>
                    <day>8</day>
                    <month>Październik</month>
                    <year>2019</year>
                </releaseDate>
                <developer>Bithell Games</developer>
                <relatedPlatforms>
                    <relatedPlatform id="p4"/>
                </relatedPlatforms>
                <publisher>Good Shepherd Entertainment / Gambitious</publisher>
				<rating source="IGN Entertainment" max="10">6.8</rating>
				<PEGI label="brak danych"/> 
                <coverArt src="id5.jpg"/>
            </game>

            <game id="game6">
                <title language="angielski">Doom</title>
                <price currency="zł">30.99</price>
                <relatedGenre id="g6"/>
                <releaseDate>
                    <day>10</day>
                    <month>Grudzień</month>
                    <year>1993</year>
                </releaseDate>
                <developer>id Software</developer>
                <relatedPlatforms>
                    <relatedPlatform id="p4"/>
                    <relatedPlatform id="p2"/>
                    <relatedPlatform id="p1"/>
                    <relatedPlatform id="p5"/>
                    <relatedPlatform id="p8"/>
                    <relatedPlatform id="p9"/>
                </relatedPlatforms>
                <publisher>id Software</publisher>
				<rating source="Metacritics" max="10">8.4</rating>
				<PEGI label="18"> 
                    <relatedPegi id="d1"/>
                    <relatedPegi id="d2"/>
				</PEGI>
                <coverArt src="id6.jpg"/>
            </game>

            <game id="game7">
                <title language="angielski">Forza Horizon 4</title>
                <price currency="zł">199.00</price>
                <relatedGenre id="g7"/>
                <releaseDate>
                    <day>2</day>
                    <month>Październik</month>
                    <year>2018</year>
                </releaseDate>
                <developer>Playground Games</developer>
                <relatedPlatforms>
                    <relatedPlatform id="p4"/>
                    <relatedPlatform id="p5"/>
                </relatedPlatforms>
                <publisher>Xbox Game Studios / Microsoft Studios</publisher>
				<rating source="Gry-Online" max="10">8.5</rating>
				<PEGI label="3"/> 
                <coverArt src="id7.jpg"/>
            </game>

            <game id="game8">
                <title language="angielski">The Forest</title>
                <price currency="zł">71.99</price>
                <relatedGenre id="g3"/>
                <releaseDate>
                    <day>16</day>
                    <month>Marzec</month>
                    <year>2010</year>
                </releaseDate>
                <developer>Endnight Games</developer>
                <relatedPlatforms>
                    <relatedPlatform id="p4"/>
                    <relatedPlatform id="p2"/>
                </relatedPlatforms>
                <publisher>Endnight Games</publisher>
				<rating source="Metacritics" max="10">7.3</rating>
				<PEGI label="18"> 
                    <relatedPegi id="d1"/>
				</PEGI>
                <coverArt src="id8.jpg"/>
            </game>

            <game id="game9">
                <title language="angielski">RoboCraft</title>
                <relatedGenre id="g8"/>
                <releaseDate>
                    <day>19</day>
                    <month>Grudzień</month>
                    <year>2013</year>
                </releaseDate>
                <developer>Freejam</developer>
                <relatedPlatforms>
                    <relatedPlatform id="p4"/>
                </relatedPlatforms>
                <publisher>Freejam</publisher>
				<rating source="Steam" max="10">7.0</rating>
				<PEGI label="odpowiednia dla każdego wieku"/> 
                <coverArt src="id9.jpg"/>
            </game>

            <game id="game10">
                <title language="angielski">Half-Life 2</title>
                <price currency="zł">139.90</price>
                <relatedGenre id="g6"/>
                <releaseDate>
